[general]
magicEnabled = false

[server]
runOnSave = true

[logger]
level = "info"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base="light"

[global]
# Utiliser Python 3.10, qui est largement compatible avec RDKit et Mordred.
python_version = 3.10
